version: '3.8'

services:
  db:
    build: ./db/
    command: postgres -c shared_preload_libraries=pg_cron -c cron.database_name=hndata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: hndata

  backend:
    build: ./api/
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/hndata"
    depends_on:
      - db

volumes:
  postgres_data: